### ISSUE TITLE
feat: Alamofire 공통 모듈 개발

### ISSUE THREAD

**Issue by peppermint100** [Ward-Group/Ward_iOS#23]
# 💡이슈 요약
Alamofire로 WardService API를 요청하기 위한 Base API 모듈 개발

# ✅ 체크리스트
- [x] Alamofire 설치
- [x] Alamofire 공통 모듈 개발

**Comment by SuniDev** [comment]
@peppermint100 인규님 혹시 Moya 라이브러리를 아시나요?
Moya 라이브러리가 Alamofire 기반으로 모듈화된 네트워킹 라이브러리인데,
Alamofire를 직접 모듈화해서 Moya 처럼 사용하는 (+네트워크 로그도 찍히게 하고~) 방법이 있어요.
저희 그렇게 모듈화 해보는게 어때요?

참고 소스는 alamofire Moya처럼 사용하기 이런식으로 검색해보시면 됩니당.

**Comment by peppermint100** [comment]
아 이걸 이제 봤네요... Moya도 한번 확인해보겠습니다

**Comment by SuniDev** [comment]
API는 추후에 붙이면서 다시 해보죠! 이 이슈는 완료로 close 하셔도 됩니다 ㅎㅎ 잘 개발 해주셔서!!
